spring:
  application:
    name: data-hub
  elasticsearch:
    rest:
      uris: 114.116.35.31:9200

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://114.116.35.31:3307/w08e-data-hub?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 1+1=caibudao.O

  redis:
    host: 114.116.35.31
    port: 6379
    database: 10
  jackson:
    # ?????
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      # ?????
      indent_output: false
      # ?????????
      fail_on_empty_beans: false
    deserialization:
      # ??????json???????
      fail_on_unknown_properties: false

rocketmq:
  consumer:
    group: w08e_data_hub_city_group
    # 一次拉取消息最大值，注意是拉取消息的最大值而非消费最大值
    pull-batch-size: 10
  name-server: 114.116.35.31:9876
  producer:
    # 发送同一类消息的设置为同一个group，保证唯一
    group: springboot_producer_group
    # 发送消息超时时间，默认3000
    sendMessageTimeout: 10000
    # 发送消息失败重试次数，默认2
    retryTimesWhenSendFailed: 2
    # 异步消息重试此处，默认2
    retryTimesWhenSendAsyncFailed: 2
    # 消息最大长度，默认1024 * 1024 * 4(默认4M)
    maxMessageSize: 4096
    # 压缩消息阈值，默认4k(1024 * 4)
    compressMessageBodyThreshold: 4096
    # 是否在内部发送失败时重试另一个broker，默认false
    retryNextServer: false


server:
  port: 8088
#sa-token:
#  token-name: satoken
#  timeout: 2592000
#  active-timeout: -1
#  is-concurrent: true
#  is-share: true
#  token-style: uuid
#  is-log: true


logging:
  level:
    org.springframework.web.servlet.DispatcherServlet: DEBUG